name: paribu_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  retrofit: ^4.4.2
  get_it: ^8.0.3
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  bip39: ^1.0.6
  web3dart: ^2.7.3
  encrypt: ^5.0.0
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  fl_chart: ^0.70.2
  reown_walletkit: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - .env.dev 
    - .env.prod